#pragma once

#include "core/Matrix4.h"
#include "core/Section.h"

namespace slm
{

    /// Section on the sign of D and on how it sits relative to a direction
    /// dependent involution.
    class LiteraturePosition : public Section
    {
    public:
        /// Direction dependent involution for the axis choice theta = phi = 0,
        /// which swaps t and z with a sign.
        static Matrix4 zaopoLambdaInfinity();

        /// Whether D lies in the extended group generated by that involution.
        /// \return False, because of the reflection D contains.
        static bool isInZaopoGroup();

        /// Three dimensional determinant of the x <-> y swap inside D.
        /// \return -1, so the swap is not an element of SO(3).
        static double xySwapDeterminant3D();

        std::string number() const override { return "18.10"; }
        std::string title() const override
        {
            return "Sign choice and the structure of D";
        }
        void run(Report &report) const override;
    };

}
