#pragma once

#include "core/Matrix4.h"
#include "core/Section.h"

namespace slm
{

    /// Position of the involution D relative to a direction dependent
    /// extension of the Lorentz group.
    ///
    /// One way to extend the Lorentz group past the speed of light is to
    /// adjoin a direction dependent involution, one for each choice of axis,
    /// which swaps the time coordinate with the spatial one along that
    /// direction. The extended group is then generated by that involution
    /// together with the proper orthochronous transformations.
    ///
    /// D is a different object: it also permutes the two remaining space axes,
    /// and that permutation is a reflection rather than a rotation, so D does
    /// not lie in the extended group. These functions establish that, and check
    /// the separate question of whether D and its negative can be told apart at
    /// all by the conditions imposed on them.
    class ExtendedLorentzGroup : public Section
    {
    public:
        /// The direction dependent involution for the axis choice
        /// theta = phi = 0, which swaps t and z with a sign.
        static Matrix4 lambdaAlongZ();

        /// Whether D lies in the group generated by that involution together
        /// with the proper orthochronous Lorentz transformations.
        /// \return False, because of the reflection D contains.
        static bool isInExtendedGroup();

        /// Three dimensional determinant of the x <-> y swap inside D.
        /// \return -1, so the swap is not an element of SO(3).
        static double xySwapDeterminant3D();

        std::string title() const override
        {
            return "Sign choice, and where D sits relative to the extended Lorentz group";
        }
        void run(Report &report) const override;
    };

}
